### ISSUE TITLE
Update LineItem API call fails with sequence.

### ISSUE THREAD

**Issue by hisea** [thewizarodofoz/google-ad-manager-api#3]
I'm trying to update dfp with a custom targeting section looks like this:

```	
"targeting": {
		"inventoryTargeting": {
			"targetedAdUnits": [{
				"adUnitId": "12341234",
				"includeDescendants": true
			}]
		},
		"requestPlatformTargeting": "",
		"customTargeting": {
			"logicalOperator": "OR",
			"children": [{
				"logicalOperator": "AND",
				"children": [{
					"operator": "IS",
					"audienceSegmentIds": ["12341234"],
					"attributes": {
						"xsi:type": "AudienceSegmentCriteria"
					}
				}],
				"attributes": {
					"xsi:type": "CustomCriteriaSet"
				}
			}]
		}
	}
```

above generated the following xml when debugging:
```
                <targeting>
                    <inventoryTargeting>
                        <targetedAdUnits>
                            <adUnitId>12341234</adUnitId>
                            <includeDescendants>true</includeDescendants>
                        </targetedAdUnits>
                    </inventoryTargeting>
                    <requestPlatformTargeting></requestPlatformTargeting>
                    <customTargeting>
                        <logicalOperator>OR</logicalOperator>
                        <children xsi:type="CustomCriteriaSet">
                            <logicalOperator>AND</logicalOperator>
                            <children xsi:type="AudienceSegmentCriteria">
                                <operator>IS</operator>
                                <audienceSegmentIds>12341234</audienceSegmentIds>
                            </children>
                        </children>
                    </customTargeting>
                </targeting>
```

This has failed the request with error
```
soap:Client: Unmarshalling Error: cvc-complex-type.2.4.d: Invalid content was found starting with element 'customTargeting'. No child element is expected at this point.
```

With some trial and error and more manual testing, I think the `                   <requestPlatformTargeting></requestPlatformTargeting>`
needs to be the last child under `targeting`. I was reading `node-soap` documentation and source code and couldn't find a way to get the proper ordering to show up in the xml.

Just wondering if @thewizarodofoz or anyone else has similar issue and has a successful resolution?

Thanks

**Comment by thewizarodofoz** [comment]
@hisea I think the problem is `"requestPlatformTargeting": ""`. If you do not need `requestPlatformTargeting` don't include it in the request payload at all. An empty string is not a valid value for that field.

Also, note that SOAP is order-sensitive. Meaning you must include fields in the order the are described in the [docs](https://developers.google.com/ad-manager/api/reference/v201908/LineItemService.Targeting). For example, if you did want to include `requestPlatformTargeting` it has to be last in the `targeting` object.
So this **will not work** (because `requestPlatformTargeting` has to be last):
```js
{
    targeting: {
        requestPlatformTargeting: {
            targetedRequestPlatforms: ["BROWSER"]
        },
        customTargeting: {
            ...
        },
    }
}
```

But this **will work**:
```js
{
    targeting: {
        "customTargeting": {
            ...
        },
        requestPlatformTargeting: {
            targetedRequestPlatforms: ["BROWSER"]
        },
    }
}
```

**Comment by hisea** [comment]
Thanks @thewizarodofoz I will try your method, I know the ordering is important but couldn't find out how to specify an order for js object.  I thought the order of the object attribute is not guaranteed .

currently i was doing the following hoping the time of assignment will affect the order but it does not.
```
  targeting.customTargeting = {....}
  targeting.requestPlatformTargeting = {...}
```
I will try your way, to specify as an object literal with fixed ordering see if i have any luck and report back my findings. 

I was hoping the `node-soap` packaging would respect the `sequence` element in the `wsdl` or have an option to specify the order for xml so it will read the object keys in that order.

**Comment by hisea** [comment]
Yeah, it seems the ordering is not guaranteed.

When i created the object it looks like the order is correct.
<img width="771" alt="Screen Shot 2019-09-22 at 6 03 41 PM" src="https://user-images.githubusercontent.com/118958/65395240-2f364800-dd66-11e9-9e4f-34f88071e4a5.png">

but when `soap` is processing it it looks like the order has changed:
<img width="682" alt="Screen Shot 2019-09-22 at 6 09 52 PM" src="https://user-images.githubusercontent.com/118958/65395277-a966cc80-dd66-11e9-97a6-68f5e3bbad5a.png">

Also I think the `requestPlatformTargeting` part was fine with empty string. if I remove `customTargeting` part everything went through fine.
