### ISSUE TITLE
Would it be all right if I added an examples folder

### ISSUE THREAD

**Issue by chriskinsman** [thewizarodofoz/google-ad-manager-api#9]
Add contributed an example on how to run a report job, get the status and then download the results?

Only downside I can see is it could add some dependencies like GoogleAuth, Request, etc

Happy to contribute it as non-executable documentation in README.md also.  Took me awhile to figure out so love to help other folks avoid the time sink.

**Comment by thewizarodofoz** [comment]
@chriskinsman yes please go ahead

**Comment by ritter** [comment]
@chriskinsman I'm looking for examples regarding report jobs.  Do you still have anything you can contribute?

**Comment by ritter** [comment]
I just figured out that the order of ReportQuery properties is very important.

For me it was:

1. dimensions
2. adUnitView
3. columns
4. dimensionAttribues
5. dateRangeType

**Comment by chriskinsman** [comment]
Would have to extract some code from production.  Probably won't get to it
for a week or so...
